### ISSUE TITLE
HTML-tag props are not inherited in Text component

### ISSUE THREAD

**Issue by chelentos** [gravity-ui/uikit#1581]
For example I want to write something like this:

```tsx
<Text as="label" htmlFor="someId">label text</Text>
```
But i'm getting ts error about not existing prop.

<details><summary>Error example</summary>
<code>Property 'htmlFor' does not exist on type 'IntrinsicAttributes & { as?: "label" | undefined; } & Omit<TextProps, "as"> & { ref?: ((instance: HTMLLabelElement | null) => void) | RefObject<HTMLLabelElement> | null | undefined; }'</code>
</details>

**Comment by korvin89** [comment]
сс @IsaevAlexandr

**Comment by chelentos** [comment]
Resolved [here](https://github.com/gravity-ui/uikit/pull/1584)

**Comment by baikinkirill** [comment]
Hi! We are using version uikit 6.23.0 and components 3.7.0. We still have an error when using the "as" prop in the Text component:

```
export const Text: <C="span" extends any>({ref, ...props}: (TextProps<C> & Omit<React.PropsWithoutRef<React.ComponentProps<C>>, keyof TextProps<T>> & {ref?: TextRef<C> | undefined})) => React.ReactElement
```
